name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6.x'

    - name: Install package
      run: |
        python -m pip install --upgrade pip setuptools
        pip install .
    - name: Run unit tests
      run: |
        pytest -m "not integtest" --cov=tanuki __tests__/
    - name: Run integration tests
      run: |
        pytest -m integtest --cov=tanuki __tests__/