name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'
    - name: Install package
      run: |
        python -m pip install --upgrade pip setuptools
        pip install .
    - name: Install test dependencies
      run: |
        pip install ".[tests]"
    - name: Run tests
      run: |
        pytest
